# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta12
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: us-east4-docker.pkg.dev/doctornow-84c00/containers/dn-booking-api
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
